PRE_COMMANDS:
  - command: >
      pip install --upgrade pip --root-user-action=ignore &&
      python3 -m pip install --no-cache-dir -r /tmp/lint/requirements.txt
    venv: pylint
    continue_if_failed: false
DISABLE_LINTERS:
  # Disabling black as I do not agree with the formatting
  - PYTHON_BLACK
  # markdown tables are formatted with prettier
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
