name: Python Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout code
        # Accept Unpinned Actions Full Length Commit SHA
        # As we trust the merge and release process of Actions/
        # kics-scan ignore-line
        uses: actions/checkout@v4
      - name: Set up Python
        # Accept Unpinned Actions Full Length Commit SHA
        # As we trust the merge and release process of Actions/
        # kics-scan ignore-line
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest --verbose
