name: Python Tests

# Trigger the workflow when a PR is opened, synchronized (updated), or reopened
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    # Define the operating system and the Python version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python with the version from the matrix
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run your tests
      - name: Run tests
        run: |
          python -m pytest tests/test_files.py