# Disable: Unpinned Actions Full Length Commit SHA
# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: Release
on:
  push:
    tags:
      - v*.*.*
permissions:
  contents: write
  discussions: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir annotations
          cp -r local/ annotations/local/
          zip -r annotations.zip annotations/
      - name: Release zip
        uses: softprops/action-gh-release@v2
        with:
          files: annotations.zip
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - id: setup-steamcmd
        # Accept Unpinned Actions Full Length Commit SHA
        # As we trust the merge and release process of CyberAndrii/
        # kics-scan ignore-line
        uses: CyberAndrii/setup-steamcmd@v1.2.0
      - id: setup-steam-config
        env:
          STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIG_VDF }}
        run: |
          STEAM_DIR="${{ steps.setup-steamcmd.outputs.directory }}"
          CONFIG_DIR="$STEAM_DIR/config"
          CONFIG_PATH="$CONFIG_DIR/config.vdf"
          mkdir -p $CONFIG_DIR
          echo "$STEAM_CONFIG_VDF" | base64 -d > $CONFIG_PATH
          chmod 700 $CONFIG_PATH
          ls -halt $STEAM_DIR
      - id: update_workshop
        run: |
          python src/workshop.py --steam_account_name ${{ secrets.STEAM_ACCOUNT_NAME }} --steam_cmd ${{ steps.setup-steamcmd.outputs.executable }}
